### ISSUE TITLE
Illegal characters in path in `SourceFiles` when trying to open a netstandard1.6 project

### ISSUE THREAD

**Issue by glitch100** [phmonte/Buildalyzer#112]
When running the following:
```
AnalyzerManager manager = new AnalyzerManager();
ProjectAnalyzer analyzer = manager.GetProject(projectPath);
AdhocWorkspace workspace = new AdhocWorkspace();
Project roslynProject = analyzer.AddToWorkspace(workspace);
```
Where:
`projectPath` = a `.csproj` targetting `netstandard1.6`

The commandLine arguments contain:
`dotnet exec "C:\Program Files\dotnet\sdk\2.2.202\Roslyn\bincore\csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 `
This gets converted to:
![image](https://user-images.githubusercontent.com/1757590/58545113-841fe280-81fa-11e9-8bed-dccec14d47a6.png)

The first entry causes a `Illegal characters in Path` via the `Path.GetFileName` call when attempting to get the `SourceFiles` property in the `AnalyzerResult` class as part of the `AddToWorkspace` call. I suspect this is because of the `dotnet exec` prefix. 

Feels like the Processing of these arguments should trim a `dotnet exec` call, but I might be wrong and just have the incorrect setup.

**Comment by phmonte** [comment]
Hello, I couldn't reproduce, are you still having the problem?

**Comment by phmonte** [comment]
Closing the issue due to lack of feedback, if the problem persists, please open a new one.
