### ISSUE TITLE
Could not load file or assembly 'MsBuildPipeLogger.Logger;  Cannot emit debug information for a source text without encoding;

### ISSUE THREAD

**Issue by MaxEden** [phmonte/Buildalyzer#173]
Hi! 
There is an issue with workspaces: without setting source text encoding explicitly you cant emit pdb
https://github.com/dotnet/roslyn/issues/24045

So I tried to make a PR and tried to build Buildalyzer from source, but it seams I hit the known issue with MsBuildPipeLogger
I don't really understand why it's not being copied to the output.

If somebody helps me to resolve any of these issues, I will be really grateful.

**Comment by phmonte** [comment]
Hi @MaxEden, I can help you, do you still need it?

**Comment by phmonte** [comment]
Closing the issue due to lack of feedback, if the problem persists, please open a new one.
