### ISSUE TITLE
use AddToWorkspace throw Exception System.ArgumentException:The specified sequence has duplicates parameter name projectReferences[11]

### ISSUE THREAD

**Issue by benxionghu** [phmonte/Buildalyzer#180]
AnalyzerManager manager = new AnalyzerManager(files[0]);
  analyzer.AddToWorkspace(workspace);
  exception message:
System.ArgumentException:The specified sequence has duplicates parameter name projectReferences[11]
   在 Microsoft.CodeAnalysis.PublicContract.ThrowArgumentItemNullOrDuplicateException[T](IEnumerable`1 sequence, String argumentName) 位置 /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/PublicContract.cs:行号 150
   在 Microsoft.CodeAnalysis.ProjectInfo.Create(ProjectId id, VersionStamp version, String name, String assemblyName, String language, String filePath, String outputFilePath, CompilationOptions compilationOptions, ParseOptions parseOptions, IEnumerable`1 documents, IEnumerable`1 projectReferences, IEnumerable`1 metadataReferences, IEnumerable`1 analyzerReferences, IEnumerable`1 additionalDocuments, Boolean isSubmission, Type hostObjectType, String outputRefFilePath) 位置 /_/src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs:行号 220
   在 Buildalyzer.Workspaces.AnalyzerResultExtensions.GetProjectInfo(IAnalyzerResult analyzerResult, Workspace workspace, ProjectId projectId)
   在 Buildalyzer.Workspaces.AnalyzerResultExtensions.AddToWorkspace(IAnalyzerResult analyzerResult, Workspace workspace, Boolean addProjectReferences)
Why does this happen?

**Comment by phmonte** [comment]
Hello, does the problem still happen with the new versions?

**Comment by phmonte** [comment]
Closing the issue due to lack of feedback, if the problem persists, please open a new one.
