### ISSUE TITLE
FileFormat Version not supported

### ISSUE THREAD

**Issue by colombod** [phmonte/Buildalyzer#184]
How can I handle binlog file version changes? I get this error (using .NET 6)

Unsupported log file format. Latest supported version is 9, the log file has version 14.

**Comment by daveaglick** [comment]
That actually doesn’t look like an error from my code - I’m going to guess it’s coming from the MSBuild.StructuredLogger package which is currently at 2.1.113. The latest of that package is 2.1.507, so maybe as simple as updating the ref 🤞. I’ll try to take a look soon.

**Comment by daveaglick** [comment]
I updated the MSBuild.StructuredLogger package and added a .NET 6.0 project to the test suite. It runs okay, so I'm not seeing a repro at the moment. Are you able to check out the latest codebase and see if that resolves the issue? If not, any way you could point me in the right direction for a repro?

**Comment by colombod** [comment]
when I run the tests of Try.Net  I get that issue unless I drop a global.json. are you publishing new version of Byuildalyzer?

**Comment by colombod** [comment]
this is the PR I am working on https://github.com/dotnet/try/pull/953

**Comment by daveaglick** [comment]
>are you publishing new version of Buildalyzer?

Not yet - want to make sure the issue with .NET 6 and binary log versions is resolved before publishing. Any change you could build Buildalyzer from source and try it within that PR so see if the error is resolved? I'm not seeing errors on .NET 6 test projects in my integration tests, so that's encouraging.

**Comment by colombod** [comment]
We are having a lot os request to address the issue, this dotnet/try#938 is just one. I am trying to unblock these users, might need you help with it :)

**Comment by daveaglick** [comment]
Please try the newly release Buildalyzer v3.2.3 package and let me know if that resolves the issues you're seeing.

**Comment by phmonte** [comment]
@colombod, do you have any updates?

**Comment by phmonte** [comment]
Closing this issue, if necessary, open a new one please.
