### ISSUE TITLE
cannot compile local references

### ISSUE THREAD

**Issue by McP4nth3r** [phmonte/Buildalyzer#193]
When i compile, with your tool. I cannot execute class library that includes local references from other folder.
Is there a way to Include them in the builded dll file?

**Comment by daveaglick** [comment]
I'm not sure I'm totally following the problem you're having. Can you provide a little more information?

- How are you calling Buildalyzer (code samples, etc.)?
- What is your expectation in terms of results and output?
- What's actually happening that's different than your expectation?

Thanks!

**Comment by McP4nth3r** [comment]
any idea?

**Comment by phmonte** [comment]
Hello @McP4nth3r, did you manage to solve it? If not, can you upload an example of the project?
It could be several factors, I can't help with the class alone.

**Comment by McP4nth3r** [comment]
> Hello @McP4nth3r, did you manage to solve it? If not, can you upload an example of the project? It could be several factors, I can't help with the class alone.

To be quite frank, my memory of what I originally used Buildalyzer for is pretty hazy. I'm a bit in the fog as to whether this particular tool played a role in any of our projects, and if so, in which. Similarly, it's no longer clear to me whether we developed our own solution as a team or whether we ultimately switched to an alternative tool. This uncertainty probably reflects the dynamic nature of our project work. Nevertheless, I would like to express my appreciation for your efforts and the time you have invested. Your help is always much appreciated, even if the details sometimes take a back seat. 
Thanks for your effort :)
