### ISSUE TITLE
How to do a (fast) design-time build?

### ISSUE THREAD

**Issue by safesparrow** [phmonte/Buildalyzer#217]
Hi,
Thanks for this project, it makes things easier for me!

How does one do a design-time build using Buildalyzer?
It seems to me that the following does either a full build, or it does a design-time build in a very inefficient way:
```fsharp
let m = AnalyzerManager()
let p = manager.GetProject(projFile)
let r = analyzer.Build()
```
Running this for the `FSharp.Compiler.Service.fsproj` project in the F# compiler takes 57s.

I couldn't find any options that would allow me to say what kind of build I want to run. What am I missing?

EDIT: I think I found it:
```fsharp
let m = AnalyzerManager()
let p = m.GetProject(projPath)
let be = p.EnvironmentFactory.GetBuildEnvironment()
let be2 = BuildEnvironment(true, false, [||], be.MsBuildExePath, be.DotnetExePath, be.Arguments)
let r = p.Build(be2)
```

**Comment by safesparrow** [comment]
Actually my 'fix' doesn't work - it gives empty results (eg. no source files).

So still an open question for me as to how to do quick design-time builds.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the explanation @daveaglick.

@safesparrow I am using Buildalyzer with Fable, I take the compiler options directly by splitting the lines of result.Command and it works (source files are lines not starting with a hyphen).

**Comment by safesparrow** [comment]
> Thanks a lot for the explanation @daveaglick.
> 
> @safesparrow I am using Buildalyzer with Fable, I take the compiler options directly by splitting the lines of result.Command and it works (source files are lines not starting with a hyphen).

That should work - the main issue with it is that it actually performs a full build, which is not something you'd normally need just to get the compiler commandline, and it can be slow due to that.

It's also not trivial to construct `FSharpOptions` objects from it, especially in a project graph, rather than just a standalone project. But I'm sure what you've done in eg. https://github.com/fable-compiler/Fable/blob/b502e14cff8b05c92253112019b22474146b5414/src/Fable.Cli/ProjectCracker.fs handles that.

**Comment by daveaglick** [comment]
> That should work - the main issue with it and the topic of this issue is that it actually performs a full build, which is not something you'd normally need just to get the compiler commandline, and it can be slow due to that.

Yeah, I'd be happy to merge in a PR that has the right set of MSBuild properties to trigger a design-time F# build, but I'm afraid without a contribution it's something that's out of my league and time availability to figure out on my own.

**Comment by safesparrow** [comment]
>Yeah, I'd be happy to merge in a PR that has the right set of MSBuild properties to trigger a design-time F# build, but I'm afraid without a contribution it's something that's out of my league and time availability to figure out on my own.

Thanks - I was just explaining why using the output of Buildalyzer for generating compiler options, while works, is not exactly what I was hoping for 👍

**Comment by phmonte** [comment]
Closing the issue due to lack of activity, if you have any updates about F#, please open a new one.
