### ISSUE TITLE
Error when trying to read dotnet --info

### ISSUE THREAD

**Issue by phmonte** [phmonte/Buildalyzer#228]
I'm getting an error when reading the dotnet --info command, at certain times my cluster takes more than 4000ms to return the dotnet --info which causes Buildalyzer to fail.

Does it make sense to implement an environment variable for custom timeout values or wait for the console to respond to some value?
I can open this PR, but I would like to know if it makes sense and if there is any preference for waiting for the console or reading the timeout of some environment variable.

Just for context, I'm using dotnet stryker which has a dependency on Buildalyzer.

[Code](https://github.com/daveaglick/Buildalyzer/blob/5b732a8ce572efbba077dd08871fb609c69f94ce/src/Buildalyzer/Environment/DotnetPathResolver.cs#L63)

[Stryker Issue](https://github.com/stryker-mutator/stryker-net/issues/2488)

**Comment by daveaglick** [comment]
#236 was merged recently, which includes your environment variable to extend the `dotnet --info` timeout. I also extended the default wait time in version 6.0.2 to 10 seconds (rolling out now). Can you try the latest 6.0.2 version and let me know if this issue is now resolved? Thanks!

**Comment by phmonte** [comment]
I'll test it and let you know, thanks.

**Comment by phmonte** [comment]
Worked perfectly.
