### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by rouke-broersma** [phmonte/Buildalyzer#248]
We are sponsoring dave because we appreciate the hard work they have put into Buildalyzer. In the future we will probably want to either move that sponsorship to you, or sponsor you as well as dave. Are you open to sponsoring? If so, could you enable sponsoring for your account?

**Comment by phmonte** [comment]
Thanks for remembering, I've already signed up and the account is under review on github, as soon as it's complete I'll update the project's readme and close the issue.

**Comment by daveaglick** [comment]
That's awesome - I removed my own sponsorship info before transferring and meant to mention you should turn it on and add yours. I fully support anyone who was sponsoring me for this project to transfer that sponsorship to @phmonte going forward!

**Comment by Corniel** [comment]
Note that the [README.md](https://github.com/phmonte/Buildalyzer/blob/main/README.md) still refers to @daveaglick's sponsor account.

**Comment by phmonte** [comment]
I believe that all the references have been updated, again thank you very much for letting me know, I confess that I hadn't even thought about it when I accepted the project, but it's certainly something that would make me happy :)
