### ISSUE TITLE
Targeting netstandard

### ISSUE THREAD

**Issue by CptWesley** [phmonte/Buildalyzer#256]
Currently the project targets .NET 6 and .NET 8. For the highest level of compatibility I would suggest targeting .netstandard. This way the package can also be used by roslyn analyzers. I'm not sure if it's possible, since I'm not that deeply versed in the MSBuild intrinsics.

**Comment by Corniel** [comment]
There are may dependencies, including `Microsoft.Build` that are not fully supported for netstandard (2.0).

```
Severity	Code	Description	Project	File	Suppression State	Line	Details
Warning	NU1701	Package 'Microsoft.Build 17.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

I'm inclined to say that this will be tricky.
