### ISSUE TITLE
Buildalyze removes alias information in result since v 7

### ISSUE THREAD

**Issue by dupdob** [phmonte/Buildalyzer#291]
Assembly aliases were available in previous Buildalyzer's versions. Alias information are no longer available since V7.
In early version, aliased assemblies appeared as `alias=assembly` references. Since V7, the `alias=` part has disappeared.

This impacts [Stryker](https://github.com/stryker-mutator/stryker-net) as it is no longer able to build project using assembly aliases.
We did implement a workaround using `Packages` information, but this works only when _AssemblyName==PackageName_ and it does not support project reference aliases at all.
I do not think reverting to previous behavior is a good idea, I propose aliases information to be available as map matching assembly pathname to their alias(es).

I am willing to work on a PR to implement this.

**Comment by Corniel** [comment]
Can you provide an example project that reproduces this issue, so that we can start from there?

**Comment by dupdob** [comment]
Here is a solution where the test project refers to the production project via an alias (aliased project reference) and uses xunit attributes via an alias (aliased package reference).
Note: the test project has to reference some xunit internal dependencies explicitly so they can be aliased.

[AliasesDemo.zip](https://github.com/user-attachments/files/17608355/AliasesDemo.zip)

**Comment by dupdob** [comment]
do you need anything else ?
do you wish me to offer a PR for this ?

**Comment by Corniel** [comment]
A PR would also be fine. @phmonte did not respond yet, which worries me a bit. I've some PR's open as well, and as he is the (new) owner of the repo, I can not release nor merge anything without his interference. :(

**Comment by phmonte** [comment]
I'll see the PRs this weekend, I'll try today.
@Corniel @dupdob
